version: '{branch}-{build}'
build: off
image: Visual Studio 2015
cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  # python envs
  - mkdir C:\venv
  - C:\Python36-x64\Scripts\virtualenv C:\venv
  - C:\venv\Scripts\activate

  - pip install --upgrade setuptools virtualenv wheel pytest
  - pip install --editable .
  - pip install --editable tests/gbtestapp

test_script:
  - pytest
